Given a bank customer, build a neural network-based classifier that can determine
whetherthey will leave or not in the next 6 months.
Dataset Description: The case study is from an open-source dataset from
Kaggle.The dataset contains 10,000 sample points with 14 distinct features
such as CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance,
etc.
Link to the Kaggle project:
https://www.kaggle.com/barelydedicated/bank-customer-churnmodeling Perform following steps:
1. Read the dataset.
2. Distinguish the feature and target set and divide the data set into training and test
sets.
3. Normalize the train and test data.
4. Initialize and build the model. Identify the points of improvement and implement the
same.
Print the accuracy score and confusion matrix (5 points).

In [6]:
# !pip install scikit-learn
%pip install keras
%pip install tensorflow
# !pip install --upgrade pip

Requirement already satisfied: keras in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (3.6.0)
Requirement already satisfied: absl-py in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (2.1.0)
Requirement already satisfied: numpy in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (2.0.2)
Requirement already satisfied: rich in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (0.0.8)
Requirement already satisfied: h5py in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (3.12.1)
Requirement already satisfied: optree in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (0.13.0)
Requirement already satisfied: ml-dtypes in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (0.4.1)
Requirement already satisfied: packaging in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (24.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from optree->keras) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from rich->keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from rich->keras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: tensorflow in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (5.28.3)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (75.3.0)
Requirement already satisfied: six>=1.12.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (1.67.1)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (3.6.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow) (0.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.1.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
import seaborn as sns

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/Advait0801/SPPU-COMP-2019-Assignments/refs/heads/ML/Neural%20Network/Churn_Modelling.csv')

In [9]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [11]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [12]:
gender = pd.get_dummies(df['Gender'] , drop_first=True)
geograpy = pd.get_dummies(df['Geography'] , drop_first=True)
df = pd.concat([df , gender , geograpy] , axis=1)
df =df.drop(['Gender' , 'Geography'] ,axis=1)
df = df.dropna()
df

      CreditScore  Age  Tenure    Balance  ...  Exited   Male  Germany  Spain
0             619   42       2       0.00  ...       1  False    False  False
1             608   41       1   83807.86  ...       0  False    False   True
2             502   42       8  159660.80  ...       1  False    False  False
3             699   39       1       0.00  ...       0  False    False  False
4             850   43       2  125510.82  ...       0  False    False   True
...           ...  ...     ...        ...  ...     ...    ...      ...    ...
9995          771   39       5       0.00  ...       0   True    False  False
9996          516   35      10   57369.61  ...       0   True    False  False
9997          709   36       7       0.00  ...       1  False    False  False
9998          772   42       3   75075.31  ...       1   True     True  False
9999          792   28       4  130142.79  ...       0  False    False  False

[10000 rows x 12 columns]

In [13]:
X = df.drop('Exited' , axis = 1) # axis = 1 is to drop te entire column
Y=df['Exited']

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-0.32622142,  0.29351742, -1.04175968, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [-0.44003595,  0.19816383, -1.38753759, ..., -1.09598752,
        -0.57873591,  1.74273971],
       [-1.53679418,  0.29351742,  1.03290776, ..., -1.09598752,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  0.91241915,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -1.09598752,
        -0.57873591, -0.57380915]])

In [15]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X,Y)

In [16]:
from keras.models import Sequential
from keras.layers import Dense

In [18]:
model = Sequential()
model.add(Dense(activation='relu' , units = 6))#input layer 
model.add(Dense(activation='relu' , units = 6)) #hidden layer
model.add(Dense(activation='sigmoid', units = 1))  #for classification
model.compile(optimizer='adam' , loss='binary_crossentropy')
model.fit(x_train , y_train , batch_size = 10 , epochs = 50)

Epoch 1/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 200us/step - loss: 0.5441
Epoch 2/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.4622
Epoch 3/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.4255
Epoch 4/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.4125
Epoch 5/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 191us/step - loss: 0.3848
Epoch 6/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3774
Epoch 7/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 191us/step - loss: 0.3632
Epoch 8/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3645
Epoch 9/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 196us/step - loss: 0.3547
Epoch 10/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3577
Epoch 11/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3488
Epoch 12/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 238us/step - loss: 0.3443
Epoch 13/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3583
Epoch 14/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3429
Epoch 15/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 200us/step - loss: 0.3325
Epoch 16/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3402
Epoch 17/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3540
Epoch 18/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 184us/step - loss: 0.3349
Epoch 19/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3473
Epoch 20/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3473
Epoch 21/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3469
Epoch 22/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3366
Epoch 23/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3334
Epoch 24/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3345
Epoch 25/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3399
Epoch 26/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 199us/step - loss: 0.3434
Epoch 27/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 195us/step - loss: 0.3361
Epoch 28/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 191us/step - loss: 0.3498
Epoch 29/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3290
Epoch 30/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3412
Epoch 31/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 195us/step - loss: 0.3408
Epoch 32/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3319
Epoch 33/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3394
Epoch 34/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3389
Epoch 35/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3365
Epoch 36/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3304
Epoch 37/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 199us/step - loss: 0.3323
Epoch 38/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3428
Epoch 39/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3345
Epoch 40/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3404
Epoch 41/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3388
Epoch 42/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3419
Epoch 43/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3248
Epoch 44/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3478
Epoch 45/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 191us/step - loss: 0.3391
Epoch 46/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 194us/step - loss: 0.3529
Epoch 47/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 197us/step - loss: 0.3339
Epoch 48/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step - loss: 0.3400
Epoch 49/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 192us/step - loss: 0.3312
Epoch 50/50
750/750 ━━━━━━━━━━━━━━━━━━━━ 0s 237us/step - loss: 0.3442

In [27]:
y_pred = model.predict(x_test)
y_pred = y_pred > 0.5

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 252us/step

In [29]:
y_pred_binary = (y_pred > 0.5).astype(int)
print(accuracy_score(y_test, y_pred_binary))

0.8628