In [1]:
%pip install keras
%pip install tensorflow

Requirement already satisfied: keras in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (3.6.0)
Requirement already satisfied: absl-py in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (2.1.0)
Requirement already satisfied: numpy in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (2.0.2)
Requirement already satisfied: rich in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (0.0.8)
Requirement already satisfied: h5py in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (3.12.1)
Requirement already satisfied: optree in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (0.13.0)
Requirement already satisfied: ml-dtypes in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (0.4.1)
Requirement already satisfied: packaging in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras) (24.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from optree->keras) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from rich->keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from rich->keras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: tensorflow in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (5.28.3)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (75.3.0)
Requirement already satisfied: six>=1.12.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (1.67.1)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (3.6.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorflow) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from keras>=3.5.0->tensorflow) (0.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.1.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /Users/soumyag/Desktop/BE Sem7/my-venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Advait0801/SPPU-COMP-2019-Assignments/refs/heads/ML/Neural%20Network/Churn_Modelling.csv')

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [6]:
df = df.drop(['RowNumber' , 'CustomerId' , 'Surname' ] , axis =1)

In [14]:
gender = pd.get_dummies(df['Gender'] , drop_first=True)
geography = pd.get_dummies(df['Geography'] ,  drop_first=True)
df = pd.concat([df , gender , geography] , axis =1)
df =df.drop(['Gender' , 'Geography'] ,axis=1)
df=df.dropna()

df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Male,Germany,Spain,Male,Germany,Spain,Male,Germany,Spain
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False,False,False,False,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True,False,False,True,False,False,True
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False,False,False,False,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False,False,False,False,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,True,False,False,True,False,False,True,False,False
9996,516,35,10,57369.61,1,1,1,101699.77,0,True,False,False,True,False,False,True,False,False
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False,False,False,False,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,True,False,True,True,False,True,True,False
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False,False,False,False,False,False,False

In [15]:
x =df.drop(['Exited'] , axis =1)
y = df['Exited']

In [18]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x = sc.fit_transform(x)

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state = 42)

In [19]:
from keras.models import Sequential
from keras.layers import Dense
from matplotlib import units
from scipy import optimize

model = Sequential()
model.add(Dense(activation='relu' , units = 6))
model.add(Dense(activation='relu' , units=6))
model.add(Dense(activation = 'sigmoid' , units=1))
model.compile(optimizer='adam', loss='binary_crossentropy')
model.fit(x_train , y_train,batch_size=10 ,epochs =50)

Epoch 1/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 214us/step - loss: 0.7123
Epoch 2/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 198us/step - loss: 0.4482
Epoch 3/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 231us/step - loss: 0.3937
Epoch 4/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step - loss: 0.3799
Epoch 5/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step - loss: 0.3675
Epoch 6/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step - loss: 0.3616
Epoch 7/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 200us/step - loss: 0.3674
Epoch 8/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step - loss: 0.3568
Epoch 9/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 199us/step - loss: 0.3495
Epoch 10/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step - loss: 0.3447
Epoch 11/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step - loss: 0.3531
Epoch 12/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step - loss: 0.3571
Epoch 13/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 199us/step - loss: 0.3576
Epoch 14/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step - loss: 0.3609
Epoch 15/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step - loss: 0.3453
Epoch 16/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 228us/step - loss: 0.3425
Epoch 17/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 204us/step - loss: 0.3521
Epoch 18/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 211us/step - loss: 0.3471
Epoch 19/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 210us/step - loss: 0.3475
Epoch 20/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 210us/step - loss: 0.3459
Epoch 21/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 206us/step - loss: 0.3503
Epoch 22/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step - loss: 0.3457
Epoch 23/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 203us/step - loss: 0.3445
Epoch 24/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 225us/step - loss: 0.3403
Epoch 25/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 197us/step - loss: 0.3421
Epoch 26/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step - loss: 0.3435
Epoch 27/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 200us/step - loss: 0.3314
Epoch 28/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 200us/step - loss: 0.3406
Epoch 29/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 200us/step - loss: 0.3399
Epoch 30/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 209us/step - loss: 0.3279
Epoch 31/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - loss: 0.3430
Epoch 32/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 211us/step - loss: 0.3328
Epoch 33/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 204us/step - loss: 0.3327
Epoch 34/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 199us/step - loss: 0.3438
Epoch 35/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step - loss: 0.3380
Epoch 36/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 198us/step - loss: 0.3285
Epoch 37/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 207us/step - loss: 0.3414
Epoch 38/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 200us/step - loss: 0.3415
Epoch 39/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 200us/step - loss: 0.3370
Epoch 40/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - loss: 0.3342
Epoch 41/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - loss: 0.3304
Epoch 42/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 213us/step - loss: 0.3227
Epoch 43/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 231us/step - loss: 0.3414
Epoch 44/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 264us/step - loss: 0.3290
Epoch 45/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 203us/step - loss: 0.3287
Epoch 46/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step - loss: 0.3312
Epoch 47/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 206us/step - loss: 0.3136
Epoch 48/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step - loss: 0.3343
Epoch 49/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 203us/step - loss: 0.3359
Epoch 50/50
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step - loss: 0.3350

In [20]:
y_pred = model.predict(x_test)
y_pred=y_pred>0.5

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step

In [24]:
from sklearn.metrics import accuracy_score


print(accuracy_score(y_test , y_pred.astype(int)))

0.86